task1
MarianKovalishin/cstd2223ki48kovalyshynmy10 pull request #1
Opened 2022-09-21 10:27 UTC by MarianKovalishin

2022-09-21 12:50 UTC, andrii-s-shpitser-lpnu-ua requested changes

2022-09-21 12:50 UTC, andrii-s-shpitser-lpnu-ua commented on README.md
> +# cstd2223ki48kovalyshynmy10
1) wrong branches
2) wrong merge direction from branch to branch
3) you removed task details - please add them back

2022-09-27 14:57 UTC, MarianKovalishin commented on README.md
> +# cstd2223ki48kovalyshynmy10
created new pull request

2022-09-27 19:15 UTC, andrii-s-shpitser-lpnu-ua commented on README.md
> +# cstd2223ki48kovalyshynmy10
Then please close this one

2022-09-28 09:30 UTC, closed without merging